// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SimuladorApi.Data;

#nullable disable

namespace SimuladorApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260503033729_AddSimulationResourcesAndOptionMetadata")]
    partial class AddSimulationResourcesAndOptionMetadata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SimuladorApi.Models.PhaseCriteriaSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CriterionName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("CriterionWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("EvaluationType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScenarioPhaseSettingId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioPhaseSettingId");

                    b.ToTable("PhaseCriteriaSettings");
                });

            modelBuilder.Entity("SimuladorApi.Models.Scenario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Constraints")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Difficulty")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<string>("Methodology")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Problem")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TargetUser")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("SimuladorApi.Models.ScenarioOption", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("ExpectedEffortLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedImpactLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExpectedViabilityLevel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImpactJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsCorrect")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxSelections")
                        .HasColumnType("integer");

                    b.Property<string>("OptionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("RiskImpact")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("TagsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("TimeCost")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioOptions");
                });

            modelBuilder.Entity("SimuladorApi.Models.ScenarioPhaseSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhaseOrder")
                        .HasColumnType("integer");

                    b.Property<decimal>("PhaseWeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioPhaseSettings");
                });

            modelBuilder.Entity("SimuladorApi.Models.ScenarioVariable", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseValue")
                        .HasColumnType("numeric");

                    b.Property<decimal>("MaxValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Methodology")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("MinValue")
                        .HasColumnType("numeric");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<string>("TargetKpi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Weight")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.ToTable("ScenarioVariables");
                });

            modelBuilder.Entity("SimuladorApi.Models.Simulation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AiFeedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CustomerExperience")
                        .HasColumnType("numeric");

                    b.Property<decimal>("DigitalMaturity")
                        .HasColumnType("numeric");

                    b.Property<string>("FeedbackRule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("GlobalScore")
                        .HasColumnType("numeric");

                    b.Property<decimal>("OperationalEfficiency")
                        .HasColumnType("numeric");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("UserId");

                    b.ToTable("Simulations");
                });

            modelBuilder.Entity("SimuladorApi.Models.SimulationAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("QuestionType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("SelectedOptionIdsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SimulationPhaseResponseId")
                        .HasColumnType("integer");

                    b.Property<string>("TextAnswer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SimulationPhaseResponseId");

                    b.ToTable("SimulationAnswers");
                });

            modelBuilder.Entity("SimuladorApi.Models.SimulationAttempt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CurrentKpisJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentPhase")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DecisionTraceJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FinalFeedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("FinalScore")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("InitialBudget")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("InitialKpisJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("InitialTimeWeeks")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("RemainingBudget")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("RemainingTimeWeeks")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("RiskLevel")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<int>("ScenarioId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("TriggeredEventsJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioId");

                    b.HasIndex("StudentId");

                    b.ToTable("SimulationAttempts");
                });

            modelBuilder.Entity("SimuladorApi.Models.SimulationKpiResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("FinalValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("InitialValue")
                        .HasPrecision(10, 2)
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("KpiName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SimulationAttemptId")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SimulationAttemptId");

                    b.ToTable("SimulationKpiResults");
                });

            modelBuilder.Entity("SimuladorApi.Models.SimulationPhaseResponse", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhaseName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Score")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int>("SimulationAttemptId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SubmittedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SimulationAttemptId");

                    b.ToTable("SimulationPhaseResponses");
                });

            modelBuilder.Entity("SimuladorApi.Models.SimulationVariableValue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ScenarioVariableId")
                        .HasColumnType("integer");

                    b.Property<int>("SimulationId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Value")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("ScenarioVariableId");

                    b.HasIndex("SimulationId");

                    b.ToTable("SimulationVariableValues");
                });

            modelBuilder.Entity("SimuladorApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("SimuladorApi.Models.PhaseCriteriaSetting", b =>
                {
                    b.HasOne("SimuladorApi.Models.ScenarioPhaseSetting", "ScenarioPhaseSetting")
                        .WithMany("Criteria")
                        .HasForeignKey("ScenarioPhaseSettingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScenarioPhaseSetting");
                });

            modelBuilder.Entity("SimuladorApi.Models.Scenario", b =>
                {
                    b.HasOne("SimuladorApi.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedByUser");
                });

            modelBuilder.Entity("SimuladorApi.Models.ScenarioOption", b =>
                {
                    b.HasOne("SimuladorApi.Models.Scenario", "Scenario")
                        .WithMany("Options")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("SimuladorApi.Models.ScenarioPhaseSetting", b =>
                {
                    b.HasOne("SimuladorApi.Models.Scenario", "Scenario")
                        .WithMany("PhaseSettings")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("SimuladorApi.Models.ScenarioVariable", b =>
                {
                    b.HasOne("SimuladorApi.Models.Scenario", "Scenario")
                        .WithMany("Variables")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Scenario");
                });

            modelBuilder.Entity("SimuladorApi.Models.Simulation", b =>
                {
                    b.HasOne("SimuladorApi.Models.Scenario", "Scenario")
                        .WithMany()
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimuladorApi.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scenario");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SimuladorApi.Models.SimulationAnswer", b =>
                {
                    b.HasOne("SimuladorApi.Models.SimulationPhaseResponse", "SimulationPhaseResponse")
                        .WithMany("Answers")
                        .HasForeignKey("SimulationPhaseResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationPhaseResponse");
                });

            modelBuilder.Entity("SimuladorApi.Models.SimulationAttempt", b =>
                {
                    b.HasOne("SimuladorApi.Models.Scenario", "Scenario")
                        .WithMany("SimulationAttempts")
                        .HasForeignKey("ScenarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimuladorApi.Models.User", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Scenario");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("SimuladorApi.Models.SimulationKpiResult", b =>
                {
                    b.HasOne("SimuladorApi.Models.SimulationAttempt", "SimulationAttempt")
                        .WithMany("KpiResults")
                        .HasForeignKey("SimulationAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationAttempt");
                });

            modelBuilder.Entity("SimuladorApi.Models.SimulationPhaseResponse", b =>
                {
                    b.HasOne("SimuladorApi.Models.SimulationAttempt", "SimulationAttempt")
                        .WithMany("PhaseResponses")
                        .HasForeignKey("SimulationAttemptId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SimulationAttempt");
                });

            modelBuilder.Entity("SimuladorApi.Models.SimulationVariableValue", b =>
                {
                    b.HasOne("SimuladorApi.Models.ScenarioVariable", "ScenarioVariable")
                        .WithMany()
                        .HasForeignKey("ScenarioVariableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SimuladorApi.Models.Simulation", "Simulation")
                        .WithMany("VariableValues")
                        .HasForeignKey("SimulationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ScenarioVariable");

                    b.Navigation("Simulation");
                });

            modelBuilder.Entity("SimuladorApi.Models.Scenario", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("PhaseSettings");

                    b.Navigation("SimulationAttempts");

                    b.Navigation("Variables");
                });

            modelBuilder.Entity("SimuladorApi.Models.ScenarioPhaseSetting", b =>
                {
                    b.Navigation("Criteria");
                });

            modelBuilder.Entity("SimuladorApi.Models.Simulation", b =>
                {
                    b.Navigation("VariableValues");
                });

            modelBuilder.Entity("SimuladorApi.Models.SimulationAttempt", b =>
                {
                    b.Navigation("KpiResults");

                    b.Navigation("PhaseResponses");
                });

            modelBuilder.Entity("SimuladorApi.Models.SimulationPhaseResponse", b =>
                {
                    b.Navigation("Answers");
                });
#pragma warning restore 612, 618
        }
    }
}
